name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload files
        uses: actions/upload-pages-artifact@v3  # ✅ Use v3 instead of v2
        with:
          path: .  # Adjust this if your files are in a subfolder

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2  # ✅ Use latest version (v2)
