name: Deploy to GitHub Pages

on:
  push:
    branches:
      - development  # Deploy from development instead of main (optional)
      - main         # Still deploy from main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload files
        uses: actions/upload-pages-artifact@v2
        with:
          path: .  # This will upload everything in your repo

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
